name: ui_kit
description: Shared UI components and theme for Diyar.
publish_to: none
version: 1.0.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
